#!/bin/bash

# Set the key file name
private_key="school"

# Generate RSA key pair with 4096 bits and passphrase "betty"
ssh-keygen -t rsa -b 4096 -f "$private_key" -N "betty"

echo "RSA key pair generated successfully."
echo "Private key saved as: $private_key"
echo "Public key saved as: ${private_key}.pub"

